language: php

php:
  - 7.4
  - 8.1

services:
  - mysql
  - postgresql

before_script:
  - mysql -u root -e 'create database chaos_test;'
  - psql -U postgres -c 'create database chaos_test;'
  - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - echo 'xdebug.mode = coverage' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install

script: bin/kahlan --config=kahlan-config.travis.php --clover=clover.xml

after_success:
  - "if [ $(phpenv version-name) = '7.4' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - "if [ $(phpenv version-name) = '7.4' ]; then php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'; fi"

env:
  global:
    secure: rtqAJ2dpi99k7S3my9on0YO7v77Led9T+httCaxOy9HMcNlMn9GKhUpPZbygBIgZJdYifdNhtVSAQXq6o2EEWm2ND2HcW8fsgahTGdEXt9tEoqSSvDuagkuZrKLHvSRxHzba6hMgWziyMel7HnkmSAnzglFq0GKYGMhijlooAYMHueHe7beScOISEbwVfXDOADZV+uJUj/OqVjkB1+y/gr8zel5OIjARpGNvVV9g+OeFfjPbHhQuMxMLiQnIoMs0gTLDoYXY5qNbClCKchLuvYotrQ7hJIW5kXCOEmOuJsRci6NmW3knH77ieFjCQDONKOlfS4SCOIT4nkCr2A99v50IZTOqqzRhpvHNkMx3lZQmeqBK7EmDTluOp/99IQYfXbyhC64iiCToHo8f5jUrjXhV8rlMjYKpkcOi+zA0pNF+iXTyHzaHsy4HICYBR16/OPW7kdAsERWEgV8SrXMMoxycFq4v2GXiqbZhwqbKcfSe2QzcoAlbAdRRMTRzSWUG5g2SHdpJb8Q1y1ZOJtVhiGuTMuLQ3NZxNdrSLjAjztuTEp7mW/kEjwVAlYqL/hBM4Z70RyidD1OMRbVW8Y+78OiIHb1m0HpKO0uxzi9PoGNLMJCAkVVU3nacQb4NNhNMXVR9XDhoVDDQ3OEKWMvK3SPFH9w8v1sm7OIXJhRi9s4=
