sudo: false
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_script:
  - mysql -e 'create database chaos_test;'
  - psql -c 'create database chaos_test;' -U postgres
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - composer install
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi

script: bin/kahlan --config=kahlan-config.travis.php --clover=clover.xml

after_success:
  - "if [ $(phpenv version-name) = '5.6' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - "if [ $(phpenv version-name) = '5.6' ]; then php ocular.phar code-coverage:upload --format=php-clover 'clover.xml'; fi"

env:
  global:
    secure: rRXn9KEdwZ598AeRKVxIIfNdPse4uZOyN22tLvS74qD9mhxHcI4I6lFFoEarL3FVrHpRzEizfJiAJopF7x74yUSTZ8iM3t4WAKzwEfGoUIigH0ZJs7h3IyDodwXpLlh1zBMaXBt1IOygL9K7krOqDeDsrNPYpXjopx50vYbg2pY8aimzB46ZSaXhf7GSY2d/HVMCNrfLWRYzx9Dw1C4x7zMfvyQSZwHY95OP8RdZPd39xca0kFuMk/JpBBRbH2uR5Ct+tE83w2wYbCZXBLKTo8kOPI3W8FmROk+WLOzq6BRmHtgeGl19o0APyB8mkF7TLwiqRNsFtPqW+1JBb+8/7Tri6P3cFXPvBwHHsECwOYpJ7JxFd+Tkxf9AxC4t0hcHmxs7Bb2nT+Yymon5vuEy9LgWDys5XAZVWQ92JWc46wzzSGyTr9eyJHPC/xi3Xxac7vArmpc3gIx526dYNd3Dhr+5DGozPDE/xAPzDX06Z3FsGXjMpMPVgPYR/ybTtSPktecskUVHxWlomPwY3r94k9RaawODwFiTBMYDilM9XRoTWPGInfpq1EMFpot1WVhmGa0/pF1XhcSYYIMH8JiRyGrm8aXaUsNKhHX1ejRg7DkE1iNSfDtSgfRt/xCQ7yCIYJYYK3VV5kC7UEXWKsAkfqHVdV1cJAaHhaxVkOlA4OU=
